### ISSUE TITLE
You are my hero

### ISSUE THREAD

**Issue by turismo444** [lequietriot/RuneScape-MIDI-Player-Suite#4]
This tool is the best thing ever!! Finally a way to make rs mp3's easy, even in a never before heard quality!! appreciate this a lot, thanks man! very good work

my last request to you would be, if it is possible, to implement batch conversion of midi files. it would be great if i could convert my 700 midi files at once!

and i found out that you must create a folder "MIDI Audio" in the root folder in order to be able to convert files, otherwise it gives you an exception

**Comment by lequietriot** [comment]
@turismo444 I finally got around to implementing this feature! It can be found in the Tools menu, "Batch Convert with SoundBank", this feature also removes the .mid in the wav file name and creates the MIDI Audio folder in the project root folder if it does not exist. Please let me know if you have any additional requests/ideas!
