### ISSUE TITLE
how do i run this program? i opened in in intellij and nothing for running a program file or opening a midi file in it exists.

### ISSUE THREAD

**Issue by zeakzz** [lequietriot/RuneScape-MIDI-Player-Suite#8]
title

**Comment by laserbeamorc** [comment]
+1

**Comment by lequietriot** [comment]
This program can be started by running the Main class in the project. To load a MIDI file, you just click the File tab then "Load MIDI File", then you can do whatever you would like to it. More instructions are in the ReadMe as well.

Also see previous issue:
https://github.com/lequietriot/RuneScape-MIDI-Player-Suite/issues/3
